language: c
compiler:
 - gcc
 - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get build-dep automake autoconf
# autoconf 2.69 is required for automake
 - git clone git://git.sv.gnu.org/autoconf && cd autoconf && autoreconf -ivf && ./configure && make -j24 && make -j24 check && sudo make install && cd ..
script: ./bootstrap.sh && ./configure && make -j24 && make -j24 check && sudo make install
after_failure:
 - cat test-suite.log
 - cat configure.log
